### ISSUE TITLE
可以加入五笔吗？

### ISSUE THREAD

**Issue by nofacetou** [Violin9906/my-ime#1]
百度输入法重度使用者，五笔还是他们家做得最好，另外还能支持百度用户云词库同步吗？

**Comment by Karl15926** [comment]
Chrome OS不是自带五笔么？

**Comment by nofacetou** [comment]
是自带五笔，但不是五笔拼音，要切换，而且也没有百度云词库了

**Comment by Violin9906** [comment]
暂时没有考虑加入五笔，并且，百度的api不是开源的所以早晚是要弃用的，现在太依赖网络连接了。
